import assert from "node:assert/strict"
import { execFile } from "node:child_process"
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises"
import os from "node:os"
import path from "node:path"
import test from "node:test"
import { promisify } from "node:util"

const execFileAsync = promisify(execFile)
const cli = path.resolve(".test-dist", "src", "cli.js")

test("CLI renders, explains, lists, and checks profiles", async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), "mdcsp-cli-"))
  try {
    await mkdir(path.join(root, "profiles"), { recursive: true })
    await mkdir(path.join(root, "snippets"), { recursive: true })
    await writeFile(path.join(root, "profiles", "default.toml"), 'version = 1\nname = "default"\nsnippets = ["common", "conditional"]\n')
    await writeFile(path.join(root, "snippets", "common.md"), "# Common\n")
    await writeFile(path.join(root, "snippets", "conditional.md"), '+++\ndescription = "Unavailable"\nrequires = ["not-on-path"]\n+++\n# Conditional\n')
    const target = path.join(root, "AGENTS.md")
    const env = { ...process.env, PATH: "" }

    const listed = await execFileAsync(process.execPath, [cli, "list", "profiles", "--root", root], { env })
    assert.equal(listed.stdout, "default\n")

    const explained = await execFileAsync(process.execPath, [cli, "explain", "--root", root], { env })
    assert.match(explained.stdout, /\+ .*common\.md: selected/)
    assert.match(explained.stdout, /- .*conditional\.md: missing commands: not-on-path — Unavailable/)

    await execFileAsync(process.execPath, [cli, "render", "--root", root, "--target", target], { env })
    assert.match(await readFile(target, "utf8"), /Generated by mdcsp[\s\S]*# Common/)
    assert.doesNotMatch(await readFile(target, "utf8"), /# Conditional/)

    await execFileAsync(process.execPath, [cli, "check", "--root", root, "--target", target], { env })
    await writeFile(target, "drift\n")
    await assert.rejects(
      execFileAsync(process.execPath, [cli, "check", "--root", root, "--target", target], { env }),
      (error: unknown) => Boolean(error && typeof error === "object" && "code" in error && error.code === 1),
    )
  } finally {
    await rm(root, { recursive: true, force: true })
  }
})

test("CLI reports usage errors with exit code 2", async () => {
  await assert.rejects(
    execFileAsync(process.execPath, [cli, "unknown"]),
    (error: unknown) => Boolean(
      error && typeof error === "object" && "code" in error && error.code === 2 && "stderr" in error && /Unknown command/.test(String(error.stderr)),
    ),
  )
})
