import assert from "node:assert/strict"
import { execFile } from "node:child_process"
import { access, mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises"
import os from "node:os"
import path from "node:path"
import { promisify } from "node:util"
import { fileURLToPath } from "node:url"

const execFileAsync = promisify(execFile)
const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)))
const tempRoot = await mkdtemp(path.join(os.tmpdir(), "mdcc-package-"))

try {
  const packDir = path.join(tempRoot, "pack")
  const installDir = path.join(tempRoot, "install")
  const configRoot = path.join(tempRoot, "config")
  await Promise.all([
    mkdir(packDir),
    mkdir(installDir),
    mkdir(path.join(configRoot, "profiles"), { recursive: true }),
    mkdir(path.join(configRoot, "snippets"), { recursive: true }),
  ])
  const packed = await run("npm", ["pack", "--json", "--pack-destination", packDir], root)
  const result = JSON.parse(packed.stdout.trim())
  assert.equal(result.length, 1)
  const artifact = result[0]
  const paths = artifact.files.map(file => file.path).sort()
  for (const required of [
    "LICENSE",
    "README.md",
    "SECURITY.md",
    "THIRD_PARTY_NOTICES.md",
    "dist/cli.js",
    "dist/compose.js",
    "dist/index.d.ts",
    "dist/index.js",
    "dist/output.js",
    "dist/profile.js",
    "package.json",
  ]) assert(paths.includes(required), `packed artifact is missing ${required}`)
  assert(!paths.some(entry => entry.startsWith("src/")), "source tree leaked into package")
  assert(!paths.some(entry => entry.startsWith("test/")), "test tree leaked into package")
  assert(!paths.some(entry => entry.startsWith(".test-dist/")), "test build leaked into package")
  assert.deepEqual(artifact.bundled, [], "dependencies must not be bundled")

  await writeFile(path.join(installDir, "package.json"), '{"name":"mdcc-artifact-test","private":true,"type":"module"}\n')
  const tarball = path.join(packDir, artifact.filename)
  await run("npm", ["install", "--no-audit", "--no-fund", tarball], installDir)
  await run("npm", ["audit", "--omit=dev", "--audit-level=low"], installDir)
  const installedRoot = path.join(installDir, "node_modules", "mdcc")
  const installedPackage = JSON.parse(await readFile(path.join(installedRoot, "package.json"), "utf8"))
  assert.equal(installedPackage.name, "mdcc")
  assert.equal(installedPackage.version, "0.1.0")
  assert.deepEqual(installedPackage.bin, { mdcc: "dist/cli.js" })
  assert(installedPackage.dependencies?.["smol-toml"])
  for (const hook of ["preinstall", "install", "postinstall"]) {
    assert(!installedPackage.scripts?.[hook], `package must not define an ${hook} hook`)
  }
  await access(path.join(installDir, "node_modules", "smol-toml", "package.json"))

  await writeFile(path.join(configRoot, "profiles", "default.toml"), 'version = 1\nname = "default"\nsnippets = ["one"]\n')
  await writeFile(path.join(configRoot, "snippets", "one.md"), "# Installed CLI\n")
  const binary = path.join(installDir, "node_modules", ".bin", process.platform === "win32" ? "mdcc.cmd" : "mdcc")
  const help = await run(binary, ["--help"], installDir)
  assert.match(help.stdout, /mdcc render/)
  const rendered = await run(binary, ["render", "--root", configRoot, "--stdout"], installDir)
  assert.match(rendered.stdout, /Generated by mdcc[\s\S]*# Installed CLI/)

  const libraryProbe = path.join(installDir, "probe.mjs")
  await writeFile(libraryProbe, 'import { compose } from "mdcc"\nconst result = compose({ snippets: [{ source: "probe", content: "# Library" }] })\nif (result.content !== "# Library\\n") throw new Error(result.content)\n')
  await run(process.execPath, [libraryProbe], installDir)
} finally {
  await rm(tempRoot, { recursive: true, force: true })
}

async function run(command, args, cwd) {
  try {
    return await execFileAsync(command, args, {
      cwd,
      encoding: "utf8",
      maxBuffer: 16 * 1024 * 1024,
      // Windows exposes npm and installed package bins as .cmd shims. All
      // values passed here are verifier-owned paths and fixed arguments.
      shell: process.platform === "win32",
    })
  } catch (error) {
    const stdout = typeof error?.stdout === "string" ? error.stdout : ""
    const stderr = typeof error?.stderr === "string" ? error.stderr : ""
    throw new Error(`${command} ${args.join(" ")} failed\n${stdout}${stderr}`, { cause: error })
  }
}
