#!/usr/bin/env node
import os from "node:os"
import path from "node:path"
import { composeFiles } from "./compose.js"
import { outputIsCurrent, writeOutput } from "./output.js"
import { defaultConfigRoot, listProfiles, listSnippets, loadProfile } from "./profile.js"

const HELP = `mdcc — compose Markdown context files

Usage:
  mdcc render [profile] [--root DIR] [--file FILE] [--target FILE] [--stdout] [--json]
  mdcc check [profile] [--root DIR] [--file FILE] [--target FILE] [--json]
  mdcc explain [profile] [--root DIR] [--file FILE] [--json]
  mdcc list <profiles|snippets> [--root DIR] [--json]
  mdcc --help
  mdcc --version

Profiles default to "default" under $MDCC_HOME/profiles or
$XDG_CONFIG_HOME/mdcc/profiles. The default output target is
~/.codex/AGENTS.md.
`

interface CommandArgs {
  readonly profile: string
  readonly root: string
  readonly file?: string
  readonly target: string
  readonly stdout: boolean
  readonly json: boolean
  readonly remaining: readonly string[]
}

async function main(argv: readonly string[]): Promise<void> {
  const command = argv[0]
  if (!command || command === "--help" || command === "-h") {
    process.stdout.write(HELP)
    return
  }
  if (command === "--version" || command === "-v") {
    process.stdout.write("0.1.0\n")
    return
  }
  if (!["render", "check", "explain", "list"].includes(command)) {
    throw new Error(`Unknown command: ${command}`)
  }
  const parsed = parseArgs(argv.slice(1))
  if (command === "list") {
    if (parsed.remaining.length !== 1 || !["profiles", "snippets"].includes(parsed.remaining[0] ?? "")) {
      throw new Error("list requires profiles or snippets")
    }
    if (parsed.file || parsed.stdout) throw new Error("list does not accept --file or --stdout")
    const values = parsed.remaining[0] === "profiles"
      ? await listProfiles(parsed.root)
      : await listSnippets(parsed.root)
    if (parsed.json) writeJson(values)
    else for (const value of values) process.stdout.write(`${value}\n`)
    return
  }
  if (parsed.remaining.length > 1) throw new Error(`${command} accepts at most one profile name`)
  const profileName = parsed.remaining[0] ?? parsed.profile
  const profile = await loadProfile(parsed.root, profileName, parsed.file)
  const result = await composeFiles({
    paths: profile.snippetPaths,
    header: ({ digest }) =>
      `<!-- Generated by mdcc. Edit snippets, not this file.\n` +
      `     Profile: ${profileName} (${profile.profilePath})\n` +
      `     Content: sha256:${digest.slice(0, 12)} -->`,
  })
  if (command === "explain") {
    if (parsed.stdout) throw new Error("explain does not accept --stdout")
    if (parsed.json) writeJson(result.decisions)
    else printDecisions(result.decisions)
    return
  }
  if (command === "check") {
    if (parsed.stdout) throw new Error("check does not accept --stdout")
    const current = await outputIsCurrent(parsed.target, result.content)
    if (parsed.json) writeJson({ current, target: path.resolve(parsed.target), digest: result.digest, decisions: result.decisions })
    else process.stdout.write(`${current ? "current" : "different"}\t${path.resolve(parsed.target)}\n`)
    if (!current) process.exitCode = 1
    return
  }
  if (parsed.stdout) {
    if (parsed.json) throw new Error("render cannot combine --stdout and --json")
    process.stdout.write(result.content)
    return
  }
  await writeOutput(parsed.target, result.content)
  if (parsed.json) {
    writeJson({ target: path.resolve(parsed.target), digest: result.digest, decisions: result.decisions })
  } else {
    process.stdout.write(`rendered ${result.decisions.filter((decision) => decision.selected).length} snippet(s) to ${path.resolve(parsed.target)}\n`)
  }
}

function parseArgs(argv: readonly string[]): CommandArgs {
  let profile = "default"
  let root = defaultConfigRoot()
  let file: string | undefined
  let target = path.join(os.homedir(), ".codex", "AGENTS.md")
  let stdout = false
  let json = false
  const remaining: string[] = []
  for (let index = 0; index < argv.length; index++) {
    const option = argv[index]
    if (option === "--stdout") stdout = true
    else if (option === "--json") json = true
    else if (["--root", "--file", "--target", "--profile"].includes(option ?? "")) {
      const value = argv[++index]
      if (!value || value.startsWith("-")) throw new Error(`${option} requires a value`)
      if (option === "--root") root = path.resolve(value)
      else if (option === "--file") file = path.resolve(value)
      else if (option === "--target") target = path.resolve(expandHome(value))
      else profile = value
    } else if (option?.startsWith("-")) throw new Error(`Unknown option: ${option}`)
    else if (option) remaining.push(option)
  }
  return {
    profile,
    root,
    ...(file ? { file } : {}),
    target,
    stdout,
    json,
    remaining,
  }
}

function printDecisions(decisions: readonly { readonly source: string; readonly selected: boolean; readonly reason: string; readonly description?: string }[]): void {
  for (const decision of decisions) {
    process.stdout.write(
      `${decision.selected ? "+" : "-"} ${decision.source}: ${decision.reason}${decision.description ? ` — ${decision.description}` : ""}\n`,
    )
  }
}

function expandHome(value: string): string {
  return value === "~" || value.startsWith("~/") ? os.homedir() + value.slice(1) : value
}

function writeJson(value: unknown): void {
  process.stdout.write(`${JSON.stringify(value, null, 2)}\n`)
}

main(process.argv.slice(2)).catch((error: unknown) => {
  const message = error instanceof Error ? error.message : String(error)
  process.stderr.write(`mdcc: ${message}\n`)
  process.exitCode = 2
})
